name: diplomatic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.3.1
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  share: ^2.0.1
  smooth_page_indicator: ^0.2.3
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
